In [45]:
# ==========================================================
# Imports
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

import joblib
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

pd.set_option("display.max_columns", None)

In [46]:
# ==========================================================
# Load Dataset
# ==========================================================

DATASET_PATH = Path("../data/generated/master_dataset.csv")

df = pd.read_csv(DATASET_PATH)

print("Dataset Loaded Successfully")
print(df.shape)

df.head()

Dataset Loaded Successfully
(100000, 113)

,Patient_ID,Age,Age_Group,Gender,Height_cm,Weight_kg,BMI,Blood_Group,Ethnicity,Diabetes,Diabetes_Severity,Hypertension,Hypertension_Severity,Heart_Disease,Heart_Disease_Severity,Stroke,Stroke_Severity,COPD,COPD_Severity,Asthma,Asthma_Severity,Kidney_Disease,Kidney_Disease_Severity,Parkinsons,Parkinsons_Severity,Alzheimers,Alzheimers_Severity,Thyroid,Thyroid_Severity,Liver_Disease,Liver_Disease_Severity,Arthritis,Arthritis_Severity,Cancer,Cancer_Severity,Osteoporosis,Osteoporosis_Severity,Depression,Depression_Severity,Anemia,Anemia_Severity,Uses_Insulin,Uses_Metformin,Uses_Glimepiride,Uses_Amlodipine,Uses_Losartan,Uses_Aspirin,Uses_Atorvastatin,Uses_Salbutamol,Uses_Levodopa,Uses_Donepezil,Medication_Adherence,Smoking,Alcohol,Mobility,Memory_Status,Exercise_Level,Diet_Quality,Water_Intake_Liters,Baseline_Heart_Rate,Baseline_Systolic_BP,Baseline_Diastolic_BP,Baseline_SpO2,Baseline_Temperature,Baseline_Respiratory_Rate,Cardiovascular_Score,Respiratory_Score,Neurological_Score,Metabolic_Score,Mobility_Score,Sleep_Score,Health_Index,Scenario,Timestamp,Heart_Rate,Systolic_BP,Diastolic_BP,SpO2,Temperature,Respiratory_Rate,Sleep_Hours,Activity_Steps,Pulse_Pressure,MAP,Heart_Rate_Deviation,Systolic_BP_Deviation,Diastolic_BP_Deviation,SpO2_Deviation,Temperature_Deviation,Respiratory_Deviation,Sleep_Quality,Sleep_Deficit,Activity_Level,Activity_Deficit,Comorbidity_Count,High_Risk_Disease_Count,Fever_Flag,Low_Oxygen_Flag,Tachycardia_Flag,Hypertension_Flag,Vital_Abnormality_Count,Cardiovascular_Risk,Respiratory_Risk,Neurological_Risk,Metabolic_Risk,Lifestyle_Risk,Trend_Risk,Clinical_Score,Risk_Level,Alert_Level,Possible_Event,Recommendation,Confidence
0,86911C44,100,90+,Male,146,75,35.2,B-,African,0,NaN,1,Severe,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 08:00:00,75,114,74,95,36.7,16,7.3,7525,40,87.3,0,-17,-6,0,0.0,-2,Good,0.7,High,0,3,1,0,0,0,0,0,30.4,19,20,0,20,0,16.9,Stable,NaN,Stable,Continue routine monitoring.,62.2
1,86911C44,100,90+,Male,146,75,35.2,B-,African,0,NaN,1,Severe,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 09:00:00,74,113,73,95,36.7,16,6.5,3202,40,86.3,-1,-18,-7,0,0.0,-2,Average,1.5,Moderate,3798,3,1,0,0,0,0,0,33.1,19,20,0,20,0,17.7,Stable,NaN,Stable,Continue routine monitoring.,62.4
2,86911C44,100,90+,Male,146,75,35.2,B-,African,0,NaN,1,Severe,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 10:00:00,73,109,71,94,36.7,14,5.7,6390,38,83.7,-2,-22,-9,1,0.0,-4,Average,2.3,Moderate,610,3,1,0,0,0,0,0,39.4,31,20,0,20,0,22.0,Low,Watch,Stable,"Increase hydration, encourage rest, and monito...",67.5
3,86911C44,100,90+,Male,146,75,35.2,B-,African,0,NaN,1,Severe,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 11:00:00,71,107,69,94,36.7,13,8.2,6608,38,81.7,-4,-24,-11,1,0.0,-5,Good,0.0,Moderate,392,3,1,0,0,0,0,0,44.8,33,20,0,20,0,24.0,Low,Watch,Stable,"Increase hydration, encourage rest, and monito...",68.0
4,86911C44,100,90+,Male,146,75,35.2,B-,African,0,NaN,1,Severe,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,1,Moderate,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 12:00:00,74,104,68,94,36.7,14,6.3,7780,36,80.0,-1,-27,-12,1,0.0,-4,Average,1.7,High,0,3,1,0,0,0,0,0,43.9,31,20,0,20,0,23.4,Low,Watch,Stable,"Increase hydration, encourage rest, and monito...",67.8

In [47]:
print("=" * 60)

print("DATASET INFORMATION")

print("=" * 60)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

print()

print("Missing Values :", df.isnull().sum().sum())

print("Duplicate Rows :", df.duplicated().sum())

============================================================
DATASET INFORMATION
============================================================
Rows    : 100000
Columns : 113

Missing Values : 1224445
Duplicate Rows : 0

In [48]:
DROP_COLUMNS = [

    "Patient_ID",

    "Timestamp"

]

df = df.drop(columns=DROP_COLUMNS)

print(df.shape)

(100000, 111)

In [49]:
health_target = "Risk_Level"

In [50]:
alert_target = "Alert_Level"

In [51]:
X = df.drop(

    columns=[

        health_target,

        alert_target

    ]

)

y_health = df[health_target]

y_alert = df[alert_target]

In [52]:
categorical_columns = X.select_dtypes(

    include="object"

).columns.tolist()

print(categorical_columns)

print()

print("Total :", len(categorical_columns))

['Age_Group', 'Gender', 'Blood_Group', 'Ethnicity', 'Diabetes_Severity', 'Hypertension_Severity', 'Heart_Disease_Severity', 'Stroke_Severity', 'COPD_Severity', 'Asthma_Severity', 'Kidney_Disease_Severity', 'Parkinsons_Severity', 'Alzheimers_Severity', 'Thyroid_Severity', 'Liver_Disease_Severity', 'Arthritis_Severity', 'Cancer_Severity', 'Osteoporosis_Severity', 'Depression_Severity', 'Anemia_Severity', 'Medication_Adherence', 'Mobility', 'Memory_Status', 'Exercise_Level', 'Diet_Quality', 'Scenario', 'Sleep_Quality', 'Activity_Level', 'Possible_Event', 'Recommendation']

Total : 30

In [53]:
encoders = {}

for column in categorical_columns:

    encoder = LabelEncoder()

    X[column] = encoder.fit_transform(
        X[column].astype(str)
    )

    encoders[column] = encoder

In [54]:
health_encoder = LabelEncoder()

alert_encoder = LabelEncoder()

y_health = health_encoder.fit_transform(y_health)

y_alert = alert_encoder.fit_transform(y_alert)

In [55]:
X_train_health, X_test_health, y_train_health, y_test_health = train_test_split(

    X,

    y_health,

    test_size=0.20,

    random_state=42,

    stratify=y_health

)

In [56]:
X_train_alert, X_test_alert, y_train_alert, y_test_alert = train_test_split(

    X,

    y_alert,

    test_size=0.20,

    random_state=42,

    stratify=y_alert

)

In [57]:
OUTPUT_DIR = Path("../data/processed")

OUTPUT_DIR.mkdir(

    parents=True,

    exist_ok=True

)

In [58]:
joblib.dump(

    (

        X_train_health,

        X_test_health,

        y_train_health,

        y_test_health

    ),

    OUTPUT_DIR / "health_dataset.pkl"

)

joblib.dump(

    (

        X_train_alert,

        X_test_alert,

        y_train_alert,

        y_test_alert

    ),

    OUTPUT_DIR / "alert_dataset.pkl"

)

print("Processed datasets saved successfully.")

Processed datasets saved successfully.

In [59]:
ENCODER_DIR = Path("../models/encoders")

ENCODER_DIR.mkdir(

    parents=True,

    exist_ok=True

)

joblib.dump(

    encoders,

    ENCODER_DIR / "feature_encoders.pkl"

)

joblib.dump(

    health_encoder,

    ENCODER_DIR / "health_label_encoder.pkl"

)

joblib.dump(

    alert_encoder,

    ENCODER_DIR / "alert_label_encoder.pkl"

)

print("Encoders saved successfully.")

Encoders saved successfully.

In [60]:
print("=" * 60)

print("PREPROCESSING COMPLETED")

print("=" * 60)

print("Health Train :", X_train_health.shape)
print("Health Test  :", X_test_health.shape)

print()

print("Alert Train  :", X_train_alert.shape)
print("Alert Test   :", X_test_alert.shape)

print()

print("Feature Columns :", X.shape[1])

============================================================
PREPROCESSING COMPLETED
============================================================
Health Train : (80000, 109)
Health Test  : (20000, 109)

Alert Train  : (80000, 109)
Alert Test   : (20000, 109)

Feature Columns : 109

In [61]:
print("=" * 60)

print("PREPROCESSING COMPLETED")

print("=" * 60)

print("Health Train :", X_train_health.shape)
print("Health Test  :", X_test_health.shape)

print()

print("Alert Train  :", X_train_alert.shape)
print("Alert Test   :", X_test_alert.shape)

print()

print("Feature Columns :", X.shape[1])

============================================================
PREPROCESSING COMPLETED
============================================================
Health Train : (80000, 109)
Health Test  : (20000, 109)

Alert Train  : (80000, 109)
Alert Test   : (20000, 109)

Feature Columns : 109

In [62]:
# ==========================================================
# AI-Powered Elderly Healthcare
# Preprocessing Pipeline V2
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [63]:
# ==========================================================
# Load Dataset
# ==========================================================

DATASET_PATH = Path("../data/generated/master_dataset.csv")

df = pd.read_csv(
    DATASET_PATH,
    keep_default_na=False
)

print("="*60)
print("DATASET LOADED")
print("="*60)

print("Shape :", df.shape)

df.head()

============================================================
DATASET LOADED
============================================================
Shape : (100000, 113)

,Patient_ID,Age,Age_Group,Gender,Height_cm,Weight_kg,BMI,Blood_Group,Ethnicity,Diabetes,Diabetes_Severity,Hypertension,Hypertension_Severity,Heart_Disease,Heart_Disease_Severity,Stroke,Stroke_Severity,COPD,COPD_Severity,Asthma,Asthma_Severity,Kidney_Disease,Kidney_Disease_Severity,Parkinsons,Parkinsons_Severity,Alzheimers,Alzheimers_Severity,Thyroid,Thyroid_Severity,Liver_Disease,Liver_Disease_Severity,Arthritis,Arthritis_Severity,Cancer,Cancer_Severity,Osteoporosis,Osteoporosis_Severity,Depression,Depression_Severity,Anemia,Anemia_Severity,Uses_Insulin,Uses_Metformin,Uses_Glimepiride,Uses_Amlodipine,Uses_Losartan,Uses_Aspirin,Uses_Atorvastatin,Uses_Salbutamol,Uses_Levodopa,Uses_Donepezil,Medication_Adherence,Smoking,Alcohol,Mobility,Memory_Status,Exercise_Level,Diet_Quality,Water_Intake_Liters,Baseline_Heart_Rate,Baseline_Systolic_BP,Baseline_Diastolic_BP,Baseline_SpO2,Baseline_Temperature,Baseline_Respiratory_Rate,Cardiovascular_Score,Respiratory_Score,Neurological_Score,Metabolic_Score,Mobility_Score,Sleep_Score,Health_Index,Scenario,Timestamp,Heart_Rate,Systolic_BP,Diastolic_BP,SpO2,Temperature,Respiratory_Rate,Sleep_Hours,Activity_Steps,Pulse_Pressure,MAP,Heart_Rate_Deviation,Systolic_BP_Deviation,Diastolic_BP_Deviation,SpO2_Deviation,Temperature_Deviation,Respiratory_Deviation,Sleep_Quality,Sleep_Deficit,Activity_Level,Activity_Deficit,Comorbidity_Count,High_Risk_Disease_Count,Fever_Flag,Low_Oxygen_Flag,Tachycardia_Flag,Hypertension_Flag,Vital_Abnormality_Count,Cardiovascular_Risk,Respiratory_Risk,Neurological_Risk,Metabolic_Risk,Lifestyle_Risk,Trend_Risk,Clinical_Score,Risk_Level,Alert_Level,Possible_Event,Recommendation,Confidence
0,86911C44,100,90+,Male,146,75,35.2,B-,African,0,None,1,Severe,0,None,0,None,1,Moderate,0,None,0,None,0,None,1,Moderate,0,None,0,None,0,None,0,None,0,None,0,None,0,None,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 08:00:00,75,114,74,95,36.7,16,7.3,7525,40,87.3,0,-17,-6,0,0.0,-2,Good,0.7,High,0,3,1,0,0,0,0,0,30.4,19,20,0,20,0,16.9,Stable,None,Stable,Continue routine monitoring.,62.2
1,86911C44,100,90+,Male,146,75,35.2,B-,African,0,None,1,Severe,0,None,0,None,1,Moderate,0,None,0,None,0,None,1,Moderate,0,None,0,None,0,None,0,None,0,None,0,None,0,None,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 09:00:00,74,113,73,95,36.7,16,6.5,3202,40,86.3,-1,-18,-7,0,0.0,-2,Average,1.5,Moderate,3798,3,1,0,0,0,0,0,33.1,19,20,0,20,0,17.7,Stable,None,Stable,Continue routine monitoring.,62.4
2,86911C44,100,90+,Male,146,75,35.2,B-,African,0,None,1,Severe,0,None,0,None,1,Moderate,0,None,0,None,0,None,1,Moderate,0,None,0,None,0,None,0,None,0,None,0,None,0,None,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 10:00:00,73,109,71,94,36.7,14,5.7,6390,38,83.7,-2,-22,-9,1,0.0,-4,Average,2.3,Moderate,610,3,1,0,0,0,0,0,39.4,31,20,0,20,0,22.0,Low,Watch,Stable,"Increase hydration, encourage rest, and monito...",67.5
3,86911C44,100,90+,Male,146,75,35.2,B-,African,0,None,1,Severe,0,None,0,None,1,Moderate,0,None,0,None,0,None,1,Moderate,0,None,0,None,0,None,0,None,0,None,0,None,0,None,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 11:00:00,71,107,69,94,36.7,13,8.2,6608,38,81.7,-4,-24,-11,1,0.0,-5,Good,0.0,Moderate,392,3,1,0,0,0,0,0,44.8,33,20,0,20,0,24.0,Low,Watch,Stable,"Increase hydration, encourage rest, and monito...",68.0
4,86911C44,100,90+,Male,146,75,35.2,B-,African,0,None,1,Severe,0,None,0,None,1,Moderate,0,None,0,None,0,None,1,Moderate,0,None,0,None,0,None,0,None,0,None,0,None,0,None,0,0,0,1,1,0,0,1,0,1,Missed,1,0,Independent,Moderate Impairment,Low,Good,2.1,75,131,80,95,36.7,18,60.0,57.0,65.0,93.9,100,95,78.483333,Stable,2026-01-01 12:00:00,74,104,68,94,36.7,14,6.3,7780,36,80.0,-1,-27,-12,1,0.0,-4,Average,1.7,High,0,3,1,0,0,0,0,0,43.9,31,20,0,20,0,23.4,Low,Watch,Stable,"Increase hydration, encourage rest, and monito...",67.8

In [64]:
# ==========================================================
# Dataset Summary
# ==========================================================

print("="*60)
print("DATASET INFORMATION")
print("="*60)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

print()

print("Missing Values :", df.isnull().sum().sum())

print("Duplicate Rows :", df.duplicated().sum())

print()

print(df.dtypes.value_counts())

============================================================
DATASET INFORMATION
============================================================
Rows    : 100,000
Columns : 113

Missing Values : 0
Duplicate Rows : 0

int64      63
object     34
float64    16
Name: count, dtype: int64

In [65]:
# ==========================================================
# Remove Non-ML Columns
# ==========================================================

DROP_COLUMNS = [

    "Patient_ID",

    "Timestamp"

]

df = df.drop(columns=DROP_COLUMNS)

print("="*60)
print("AFTER COLUMN REMOVAL")
print("="*60)

print(df.shape)

============================================================
AFTER COLUMN REMOVAL
============================================================
(100000, 111)

In [66]:
# ==========================================================
# Save Clean Dataset
# ==========================================================

clean_df = df.copy()

print(clean_df.shape)

(100000, 111)

In [67]:
# ==========================================================
# Health Risk Model Dataset
# ==========================================================

health_df = clean_df.copy()

HEALTH_TARGET = "Risk_Level"

HEALTH_DROP = [

    "Risk_Level",

    "Alert_Level",

    "Recommendation",

    "Possible_Event",

    "Confidence",

    "Clinical_Score"

]

X_health = health_df.drop(columns=HEALTH_DROP)

y_health = health_df[HEALTH_TARGET]

print("=" * 60)
print("HEALTH MODEL DATASET")
print("=" * 60)

print("Features :", X_health.shape)
print("Target   :", y_health.shape)

============================================================
HEALTH MODEL DATASET
============================================================
Features : (100000, 105)
Target   : (100000,)

In [68]:
# ==========================================================
# Alert Prediction Dataset
# ==========================================================

alert_df = clean_df.copy()

ALERT_TARGET = "Alert_Level"

ALERT_DROP = [

    "Alert_Level",

    "Recommendation",

    "Confidence"

]

X_alert = alert_df.drop(columns=ALERT_DROP)

y_alert = alert_df[ALERT_TARGET]

print("=" * 60)
print("ALERT MODEL DATASET")
print("=" * 60)

print("Features :", X_alert.shape)
print("Target   :", y_alert.shape)

============================================================
ALERT MODEL DATASET
============================================================
Features : (100000, 108)
Target   : (100000,)

In [69]:
# ==========================================================
# Verify Target Distribution
# ==========================================================

print("=" * 60)
print("HEALTH TARGET")
print("=" * 60)

print(y_health.value_counts())

print()

print("=" * 60)
print("ALERT TARGET")
print("=" * 60)

print(y_alert.value_counts())

============================================================
HEALTH TARGET
============================================================
Risk_Level
Low         33832
Stable      33185
Moderate    18976
High        13959
Critical       48
Name: count, dtype: int64

============================================================
ALERT TARGET
============================================================
Alert_Level
Watch               33832
None                33185
Notify Caregiver    18976
Urgent              13959
Emergency              48
Name: count, dtype: int64

In [70]:
print("=" * 60)

print("HEALTH FEATURES")

print("=" * 60)

print(len(X_health.columns))

print()

print("=" * 60)

print("ALERT FEATURES")

print("=" * 60)

print(len(X_alert.columns))

============================================================
HEALTH FEATURES
============================================================
105

============================================================
ALERT FEATURES
============================================================
108

In [71]:
# ==========================================================
# Encode Categorical Features
# ==========================================================

health_encoders = {}
alert_encoders = {}

# ---------- Health Dataset ----------

health_categorical = X_health.select_dtypes(
    include="object"
).columns

for column in health_categorical:

    encoder = LabelEncoder()

    X_health[column] = encoder.fit_transform(
        X_health[column].astype(str)
    )

    health_encoders[column] = encoder


# ---------- Alert Dataset ----------

alert_categorical = X_alert.select_dtypes(
    include="object"
).columns

for column in alert_categorical:

    encoder = LabelEncoder()

    X_alert[column] = encoder.fit_transform(
        X_alert[column].astype(str)
    )

    alert_encoders[column] = encoder

print("Health categorical columns :", len(health_categorical))
print("Alert categorical columns  :", len(alert_categorical))

Health categorical columns : 28
Alert categorical columns  : 30

In [72]:
# ==========================================================
# Encode Target Labels
# ==========================================================

health_label_encoder = LabelEncoder()
alert_label_encoder = LabelEncoder()

y_health = health_label_encoder.fit_transform(y_health)
y_alert = alert_label_encoder.fit_transform(y_alert)

print("Health Classes")
print(health_label_encoder.classes_)

print()

print("Alert Classes")
print(alert_label_encoder.classes_)

Health Classes
['Critical' 'High' 'Low' 'Moderate' 'Stable']

Alert Classes
['Emergency' 'None' 'Notify Caregiver' 'Urgent' 'Watch']

In [73]:
# ==========================================================
# Train Test Split
# ==========================================================

X_train_health, X_test_health, y_train_health, y_test_health = train_test_split(

    X_health,

    y_health,

    test_size=0.20,

    random_state=42,

    stratify=y_health

)

X_train_alert, X_test_alert, y_train_alert, y_test_alert = train_test_split(

    X_alert,

    y_alert,

    test_size=0.20,

    random_state=42,

    stratify=y_alert

)

print("Health Train :", X_train_health.shape)
print("Health Test  :", X_test_health.shape)

print()

print("Alert Train :", X_train_alert.shape)
print("Alert Test  :", X_test_alert.shape)

Health Train : (80000, 105)
Health Test  : (20000, 105)

Alert Train : (80000, 108)
Alert Test  : (20000, 108)

In [74]:
# ==========================================================
# Verify Class Balance
# ==========================================================

print("=" * 60)
print("Health Training Distribution")
print("=" * 60)

print(pd.Series(y_train_health).value_counts())

print()

print("=" * 60)
print("Health Testing Distribution")
print("=" * 60)

print(pd.Series(y_test_health).value_counts())

print()

print("=" * 60)
print("Alert Training Distribution")
print("=" * 60)

print(pd.Series(y_train_alert).value_counts())

print()

print("=" * 60)
print("Alert Testing Distribution")
print("=" * 60)

print(pd.Series(y_test_alert).value_counts())

============================================================
Health Training Distribution
============================================================
2    27066
4    26548
3    15181
1    11167
0       38
Name: count, dtype: int64

============================================================
Health Testing Distribution
============================================================
2    6766
4    6637
3    3795
1    2792
0      10
Name: count, dtype: int64

============================================================
Alert Training Distribution
============================================================
4    27066
1    26548
2    15181
3    11167
0       38
Name: count, dtype: int64

============================================================
Alert Testing Distribution
============================================================
4    6766
1    6637
2    3795
3    2792
0      10
Name: count, dtype: int64

In [75]:
# ==========================================================
# Scale Numerical Features
# ==========================================================

health_scaler = StandardScaler()
alert_scaler = StandardScaler()

# ---------- Health ----------

X_train_health_scaled = pd.DataFrame(
    health_scaler.fit_transform(X_train_health),
    columns=X_train_health.columns,
    index=X_train_health.index
)

X_test_health_scaled = pd.DataFrame(
    health_scaler.transform(X_test_health),
    columns=X_test_health.columns,
    index=X_test_health.index
)

# ---------- Alert ----------

X_train_alert_scaled = pd.DataFrame(
    alert_scaler.fit_transform(X_train_alert),
    columns=X_train_alert.columns,
    index=X_train_alert.index
)

X_test_alert_scaled = pd.DataFrame(
    alert_scaler.transform(X_test_alert),
    columns=X_test_alert.columns,
    index=X_test_alert.index
)

print("Scaling Completed Successfully")

Scaling Completed Successfully

In [76]:
# ==========================================================
# Create Output Directories
# ==========================================================

PROCESSED_DIR = Path("../data/processed")
MODEL_DIR = Path("../models")

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Folders Created Successfully")

Folders Created Successfully

In [77]:
# ==========================================================
# Save Preprocessing Objects
# ==========================================================

joblib.dump(
    health_encoders,
    MODEL_DIR / "health_feature_encoders.pkl"
)

joblib.dump(
    alert_encoders,
    MODEL_DIR / "alert_feature_encoders.pkl"
)

joblib.dump(
    health_label_encoder,
    MODEL_DIR / "health_label_encoder.pkl"
)

joblib.dump(
    alert_label_encoder,
    MODEL_DIR / "alert_label_encoder.pkl"
)

joblib.dump(
    health_scaler,
    MODEL_DIR / "health_scaler.pkl"
)

joblib.dump(
    alert_scaler,
    MODEL_DIR / "alert_scaler.pkl"
)

print("Encoders & Scalers Saved Successfully")

Encoders & Scalers Saved Successfully

In [78]:
# ==========================================================
# Save Feature Columns
# ==========================================================

joblib.dump(
    X_train_health.columns.tolist(),
    MODEL_DIR / "health_features.pkl"
)

joblib.dump(
    X_train_alert.columns.tolist(),
    MODEL_DIR / "alert_features.pkl"
)

print("Feature Lists Saved")

Feature Lists Saved

In [79]:
# ==========================================================
# Save Processed Datasets
# ==========================================================

joblib.dump(

    {

        "X_train": X_train_health_scaled,
        "X_test": X_test_health_scaled,
        "y_train": y_train_health,
        "y_test": y_test_health

    },

    PROCESSED_DIR / "health_dataset.pkl"

)

joblib.dump(

    {

        "X_train": X_train_alert_scaled,
        "X_test": X_test_alert_scaled,
        "y_train": y_train_alert,
        "y_test": y_test_alert

    },

    PROCESSED_DIR / "alert_dataset.pkl"

)

print("Processed Datasets Saved Successfully")

Processed Datasets Saved Successfully

In [80]:
# ==========================================================
# Final Verification
# ==========================================================

print("=" * 70)
print("PREPROCESSING COMPLETED SUCCESSFULLY")
print("=" * 70)

print()

print("Health Train :", X_train_health_scaled.shape)
print("Health Test  :", X_test_health_scaled.shape)

print()

print("Alert Train :", X_train_alert_scaled.shape)
print("Alert Test  :", X_test_alert_scaled.shape)

print()

print("Health Features :", len(X_train_health.columns))
print("Alert Features :", len(X_train_alert.columns))

print()

print("Files Saved In :", PROCESSED_DIR)

print("=" * 70)

======================================================================
PREPROCESSING COMPLETED SUCCESSFULLY
======================================================================

Health Train : (80000, 105)
Health Test  : (20000, 105)

Alert Train : (80000, 108)
Alert Test  : (20000, 108)

Health Features : 105
Alert Features : 108

Files Saved In : ..\data\processed
======================================================================

In [81]:
from pathlib import Path

print("Processed Files")
print(list(Path("../data/processed").glob("*")))

print()

print("Model Files")
print(list(Path("../models").glob("*")))

Processed Files
[WindowsPath('../data/processed/alert_dataset.pkl'), WindowsPath('../data/processed/health_dataset.pkl')]

Model Files
[WindowsPath('../models/alert_features.pkl'), WindowsPath('../models/alert_feature_encoders.pkl'), WindowsPath('../models/alert_label_encoder.pkl'), WindowsPath('../models/alert_scaler.pkl'), WindowsPath('../models/best_health_model.pkl'), WindowsPath('../models/encoders'), WindowsPath('../models/health_features.pkl'), WindowsPath('../models/health_feature_encoders.pkl'), WindowsPath('../models/health_label_encoder.pkl'), WindowsPath('../models/health_scaler.pkl')]

In [82]:
# ==========================================================
# Health Risk Model Dataset (Leakage-Free)
# ==========================================================

HEALTH_TARGET = "Risk_Level"

HEALTH_DROP = [

    # Target
    "Risk_Level",

    # Outputs from the rule engine
    "Alert_Level",
    "Recommendation",
    "Possible_Event",
    "Confidence",
    "Clinical_Score",

    # Intermediate risk scores (remove leakage)
    "Cardiovascular_Risk",
    "Respiratory_Risk",
    "Neurological_Risk",
    "Metabolic_Risk",
    "Lifestyle_Risk",
    "Trend_Risk"

]

health_df = clean_df.copy()

X_health = health_df.drop(columns=HEALTH_DROP)

y_health = health_df[HEALTH_TARGET]

print("Health Features :", X_health.shape)
print("Target :", y_health.shape)

Health Features : (100000, 99)
Target : (100000,)

In [83]:
# ==========================================================
# Save Processed Datasets
# ==========================================================

joblib.dump(

    {

        "X_train": X_train_health_scaled,
        "X_test": X_test_health_scaled,
        "y_train": y_train_health,
        "y_test": y_test_health

    },

    PROCESSED_DIR / "health_dataset.pkl"

)

joblib.dump(

    {

        "X_train": X_train_alert_scaled,
        "X_test": X_test_alert_scaled,
        "y_train": y_train_alert,
        "y_test": y_test_alert

    },

    PROCESSED_DIR / "alert_dataset.pkl"

)

print("Processed Datasets Saved Successfully")

Processed Datasets Saved Successfully

In [84]:
# ==========================================================
# Save Feature Columns
# ==========================================================

joblib.dump(
    X_train_health.columns.tolist(),
    MODEL_DIR / "health_features.pkl"
)

joblib.dump(
    X_train_alert.columns.tolist(),
    MODEL_DIR / "alert_features.pkl"
)

print("Feature Lists Saved")

Feature Lists Saved

In [85]:
# ==========================================================
# Save Processed Datasets
# ==========================================================

joblib.dump(

    {

        "X_train": X_train_health_scaled,
        "X_test": X_test_health_scaled,
        "y_train": y_train_health,
        "y_test": y_test_health

    },

    PROCESSED_DIR / "health_dataset.pkl"

)

joblib.dump(

    {

        "X_train": X_train_alert_scaled,
        "X_test": X_test_alert_scaled,
        "y_train": y_train_alert,
        "y_test": y_test_alert

    },

    PROCESSED_DIR / "alert_dataset.pkl"

)

print("Processed Datasets Saved Successfully")

Processed Datasets Saved Successfully

In [86]:
# ==========================================================
# Drop Unnecessary Columns
# ==========================================================

DROP_COLUMNS = [

    "Patient_ID",

    "Timestamp"

]

clean_df = df.drop(

    columns=DROP_COLUMNS

)

print(clean_df.shape)

KeyError: "['Patient_ID', 'Timestamp'] not found in axis"

In [87]:
# ==========================================================
# Save Processed Datasets
# ==========================================================

joblib.dump(

    {

        "X_train": X_train_health_scaled,
        "X_test": X_test_health_scaled,
        "y_train": y_train_health,
        "y_test": y_test_health

    },

    PROCESSED_DIR / "health_dataset.pkl"

)

joblib.dump(

    {

        "X_train": X_train_alert_scaled,
        "X_test": X_test_alert_scaled,
        "y_train": y_train_alert,
        "y_test": y_test_alert

    },

    PROCESSED_DIR / "alert_dataset.pkl"

)

print("Processed Datasets Saved Successfully")

Processed Datasets Saved Successfully

In [88]:
# ==========================================================
# Save Feature Columns
# ==========================================================

joblib.dump(
    X_train_health.columns.tolist(),
    MODEL_DIR / "health_features.pkl"
)

joblib.dump(
    X_train_alert.columns.tolist(),
    MODEL_DIR / "alert_features.pkl"
)

print("Feature Lists Saved")

Feature Lists Saved

In [89]:
# ==========================================================
# Drop Unnecessary Columns
# ==========================================================

DROP_COLUMNS = [

    "Patient_ID",

    "Timestamp"

]

clean_df = df.drop(

    columns=DROP_COLUMNS

)

print(clean_df.shape)

KeyError: "['Patient_ID', 'Timestamp'] not found in axis"